basePath: /api/v1
definitions:
  request.CreatePostRequest:
    properties:
      body:
        maxLength: 255
        minLength: 5
        type: string
      title:
        maxLength: 255
        minLength: 5
        type: string
    required:
    - body
    - title
    type: object
  request.CreateUserRequest:
    properties:
      age:
        maximum: 60
        minimum: 18
        type: integer
      email:
        maxLength: 200
        minLength: 5
        type: string
      name:
        maxLength: 200
        minLength: 5
        type: string
      password:
        maxLength: 255
        minLength: 5
        type: string
      phone:
        maxLength: 15
        minLength: 10
        type: string
      role_id:
        maximum: 2
        minimum: 1
        type: integer
      username:
        maxLength: 200
        minLength: 5
        type: string
    required:
    - age
    - email
    - name
    - password
    - phone
    - role_id
    - username
    type: object
  request.LoginUserRequest:
    properties:
      password:
        maxLength: 255
        minLength: 5
        type: string
      username:
        maxLength: 200
        minLength: 5
        type: string
    required:
    - password
    - username
    type: object
  request.UpdatePostRequest:
    properties:
      body:
        maxLength: 255
        minLength: 5
        type: string
      title:
        description: ID    int    `validate:"required" json:"post_id"`
        maxLength: 255
        minLength: 5
        type: string
    required:
    - body
    - title
    type: object
  request.UpdateUserRequest:
    properties:
      age:
        maximum: 60
        minimum: 18
        type: integer
      email:
        maxLength: 200
        minLength: 5
        type: string
      name:
        description: ID    int    `validate:"required" json:"user_id"`
        maxLength: 200
        minLength: 5
        type: string
      phone:
        maxLength: 15
        minLength: 10
        type: string
    required:
    - age
    - email
    - name
    - phone
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
      status:
        type: string
    type: object
host: localhost:8888
info:
  contact:
    email: rdbhagat999@gmail.com
    name: Ramandeep Bhagat
  description: A demo Service API in Golang using Gin Framework
  termsOfService: https://swagger.io/terms/
  title: Demo Service API
  version: 1.0.0
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login user in database
      operationId: LoginUser
      parameters:
      - description: Login user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/request.LoginUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Login user
      tags:
      - auth
  /auth/logout:
    post:
      consumes:
      - application/json
      description: Logout user in database
      operationId: Logout
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Logout user
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Save user in database
      operationId: CreateUser
      parameters:
      - description: Create user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/request.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Register user
      tags:
      - auth
  /cart/addusercart:
    post:
      consumes:
      - application/json
      description: Create cart by userId from external API
      operationId: AddCardByUserId
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Create cart by userId
      tags:
      - cart
  /cart/cartbyuser:
    get:
      consumes:
      - application/json
      description: Fetches cart by userId from external API
      operationId: GetCartByUserId
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get cart by userId
      tags:
      - cart
  /cart/deletecart:
    delete:
      consumes:
      - application/json
      description: Delete cart by cartId from external API
      operationId: DeleteCardById
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Delete cart by cartId
      tags:
      - cart
  /cart/updateusercart:
    put:
      consumes:
      - application/json
      description: Update cart by cartId from external API
      operationId: UpdateCardByUserId
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Update cart by cartId
      tags:
      - cart
  /posts:
    get:
      consumes:
      - application/json
      description: Returns a list of post
      operationId: FindAllPost
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get all post
      tags:
      - post
    post:
      consumes:
      - application/json
      description: Save post in database
      operationId: CreatePost
      parameters:
      - description: Create post
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/request.CreatePostRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Create post
      tags:
      - post
  /posts/{postId}:
    delete:
      consumes:
      - application/json
      description: Delete post from database
      operationId: DeletePost
      parameters:
      - description: Delete post by id
        in: path
        name: postId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Delete post
      tags:
      - post
    get:
      consumes:
      - application/json
      description: Returns a single post when postId maches id
      operationId: FindByIdPost
      parameters:
      - description: Find post by id
        in: path
        name: postId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get a single post by its id
      tags:
      - post
    put:
      consumes:
      - application/json
      description: Update and save post in database
      operationId: UpdatePost
      parameters:
      - description: Update post by id
        in: path
        name: postId
        required: true
        type: string
      - description: Update post
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/request.UpdatePostRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Update post
      tags:
      - post
  /posts/userposts:
    get:
      consumes:
      - application/json
      description: Returns a list of post
      operationId: FindAllByUserId
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get all post by userId
      tags:
      - post
  /users:
    get:
      consumes:
      - application/json
      description: Returns a list of users
      operationId: FindAllUser
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get all users
      tags:
      - user
  /users/{userId}:
    delete:
      consumes:
      - application/json
      description: Delete user from database
      operationId: DeleteUser
      parameters:
      - description: Delete user by id
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Delete user
      tags:
      - user
    get:
      consumes:
      - application/json
      description: Returns a single user when userId maches id
      operationId: FindByIdUser
      parameters:
      - description: Find user by id
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get a single user by its id
      tags:
      - user
    put:
      consumes:
      - application/json
      description: Update and save user in database
      operationId: UpdateUser
      parameters:
      - description: Update user by id
        in: path
        name: userId
        required: true
        type: string
      - description: Update user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/request.UpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Update user
      tags:
      - user
  /users/authuser:
    get:
      consumes:
      - application/json
      description: Get user in database
      operationId: AuthUser
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Get authenticated user
      tags:
      - user
swagger: "2.0"
